In [1]:
import numpy as np
import pandas as pd

In [2]:
dataframe_6 = pd.read_csv('data_ria_news_v2.6_from_nov_to_sept.csv', delimiter=',')
dataframe_7 = pd.read_csv('data_ria_news_v2.7_from_sept.csv', delimiter=',')
dataframe_8 = pd.read_csv('data_ria_news_v2.8_from_sept.csv', delimiter=',')
dataframe_9 = pd.read_csv('data_ria_news_v2.9_from_aug.csv', delimiter=',')
dataframe_10 = pd.read_csv('data_ria_news_v2.10_from_aug.csv', delimiter=',')

In [3]:
dataframe_8

,Unnamed: 0,Date,Text
0,0,"30 августа 2021, 22:26",Зюганов призвал выплачивать всем учителям зарп...
1,1,"30 августа 2021, 22:20",Мишустин назвал смерть журналиста Овчинникова ...
2,2,"30 августа 2021, 22:16",МЧС предупредило москвичей о грозе и порывисто...
3,3,"30 августа 2021, 21:59",Шаманизму предложили придать в России статус о...
4,4,"30 августа 2021, 21:47",ФСБ рассказала о зверствах нацистов в Киевской...
...,...,...,...
924,924,"24 августа 2021, 22:10","Синоптик пообещал, что в конце недели в Россию..."
925,925,"24 августа 2021, 21:51",Украинские паралимпийцы отказались уходить от ...
926,926,"24 августа 2021, 21:50",Онищенко предложил сформировать у школьников к...
927,927,"24 августа 2021, 21:08",Россиян предупредили о похолодании до одного г...
928,928,"24 августа 2021, 21:07",Росприроднадзор призвал участвовать в конкурсе...

In [4]:
dataframe_merged67 = pd.merge(dataframe_6, dataframe_7,  how="outer")

In [5]:
dataframe_merged67

,Unnamed: 0,Date,Text
0,0,"1 ноября 2021, 23:18","Вуйнович рассказала, когда закончится пандемия..."
1,1,"1 ноября 2021, 22:28",Военных медиков направят в Тульскую область дл...
2,2,"1 ноября 2021, 21:44",Минздраву выделят более 10 млрд рублей на лека...
3,3,"1 ноября 2021, 21:21",Ленинградская область поможет Башкирии открыть...
4,4,"1 ноября 2021, 21:15",Без справки вход воспрещен: с какими болезнями...
...,...,...,...
9662,1207,"30 августа 2021, 14:33","Врач рассказал, как проявляется лихорадка Запа..."
9663,1208,"30 августа 2021, 14:31",Путин рассказал об антителах после вакцинации
9664,1209,"30 августа 2021, 14:23",Названы темы для сочинения в 11-х классах в но...
9665,1210,"30 августа 2021, 14:17","Власти рассказали, в каком формате будут работ..."
9666,1211,"30 августа 2021, 14:17",В Рособрнадзоре рассказали об изменении числа ...

In [6]:
dataframe_merged678 = pd.merge(dataframe_merged67, dataframe_8,  how="outer")
dataframe_merged6789 = pd.merge(dataframe_merged678, dataframe_9,  how="outer")
dataframe_merged_all = pd.merge(dataframe_merged6789, dataframe_10,  how="outer")

dataframe_merged_all

,Unnamed: 0,Date,Text
0,0,"1 ноября 2021, 23:18","Вуйнович рассказала, когда закончится пандемия..."
1,1,"1 ноября 2021, 22:28",Военных медиков направят в Тульскую область дл...
2,2,"1 ноября 2021, 21:44",Минздраву выделят более 10 млрд рублей на лека...
3,3,"1 ноября 2021, 21:21",Ленинградская область поможет Башкирии открыть...
4,4,"1 ноября 2021, 21:15",Без справки вход воспрещен: с какими болезнями...
...,...,...,...
13121,829,"9 августа 2021, 15:59",В Москве пройдет благотворительный фестиваль-п...
13122,830,"9 августа 2021, 15:51",Лукашенко поручил дать гражданство иностранцам...
13123,831,"9 августа 2021, 15:46",В Нижегородской области возбудили дело о подде...
13124,832,"9 августа 2021, 15:46",В Ленинградской области мужчина с ножом ворвал...
13125,833,"9 августа 2021, 15:35",ФМБА оценило ситуацию с донорской кровью в России

In [9]:
dataframe_merged_all[dataframe_merged_all.duplicated(subset=['Date', 'Text'], keep="first")]

,Unnamed: 0,Date,Text
1561,1561,"20 октября 2021, 14:59",Путин призвал сбить темпы распространения коро...
3344,3344,"1 ноября 2021, 23:18","Вуйнович рассказала, когда закончится пандемия..."
3345,3345,"1 ноября 2021, 22:28",Военных медиков направят в Тульскую область дл...
3346,3346,"1 ноября 2021, 21:44",Минздраву выделят более 10 млрд рублей на лека...
3347,3347,"1 ноября 2021, 21:21",Ленинградская область поможет Башкирии открыть...
...,...,...,...
13121,829,"9 августа 2021, 15:59",В Москве пройдет благотворительный фестиваль-п...
13122,830,"9 августа 2021, 15:51",Лукашенко поручил дать гражданство иностранцам...
13123,831,"9 августа 2021, 15:46",В Нижегородской области возбудили дело о подде...
13124,832,"9 августа 2021, 15:46",В Ленинградской области мужчина с ножом ворвал...
13125,833,"9 августа 2021, 15:35",ФМБА оценило ситуацию с донорской кровью в России

In [46]:
df_del_dubl = dataframe_merged_all.drop_duplicates(subset=['Date', 'Text'], keep="first", inplace=False)
df_del_dubl

,Unnamed: 0,Date,Text
0,0,"1 ноября 2021, 23:18","Вуйнович рассказала, когда закончится пандемия..."
1,1,"1 ноября 2021, 22:28",Военных медиков направят в Тульскую область дл...
2,2,"1 ноября 2021, 21:44",Минздраву выделят более 10 млрд рублей на лека...
3,3,"1 ноября 2021, 21:21",Ленинградская область поможет Башкирии открыть...
4,4,"1 ноября 2021, 21:15",Без справки вход воспрещен: с какими болезнями...
...,...,...,...
13112,820,"9 августа 2021, 13:57",Врач назвала лучший способ похудения без диет
13113,821,"9 августа 2021, 13:30",В Госдуме оценили рекомендацию перевести на уд...
13114,822,"9 августа 2021, 13:30","В Приамурье за год 43 семьи получили ""земельны..."
13115,823,"9 августа 2021, 13:02",Бывшие узницы концлагерей рассказали об издева...
13116,824,"9 августа 2021, 12:57","""Ъ"": учителей и чиновников переведут на россий..."

In [47]:
df_del_dubl.to_csv("clean_ria_data.csv")

In [48]:
df_del_dubl.shape

(7910, 3)